# -*- coding: utf-8 -*-
"""openCV_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJL6wUcFhNJJyztzD_n6q9Y4HP7CNGjC
"""

import cv2
import numpy as np

from google.colab.patches import cv2_imshow

# read an image
img= cv2.imread('/content/drive/MyDrive/Hrutuja Vanjale /OpenCV/cat1.jfif')

# show an image
cv2_imshow(img)
cv2.waitKey(0)

img.shape

# grayscale
gray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

# Blur
blur= cv2.GaussianBlur(img,(5,5),cv2.BORDER_DEFAULT)
cv2_imshow(blur)

# Edge cascade
canny= cv2.Canny(img,125,255)
cv2_imshow(canny)

# Edge cascade
canny2= cv2.Canny(blur,0,255)
cv2_imshow(canny2)

# Dilating the image
dilated = cv2.dilate(canny, (7,7), iterations=3)
cv2_imshow(dilated)

# Eroding
eroded= cv2.erode(dilated,(7,7),iterations=3)
Eroded=cv2_imshow(eroded)

# resize
resized= cv2.resize(img,(500,500),interpolation=cv2.INTER_LINEAR)
resize=cv2_imshow(resized)

# Cropping
cropped = img[30:150, 130:150]
crop=cv2_imshow(cropped)

# Creating a blank picture using numpy array
blank = np.zeros(img.shape,dtype='uint8')
cv2_imshow(blank)

# Drawing on a picture
blank2= np.zeros((500,500,3),dtype='uint8')
cv2_imshow(blank2)

from google.colab.patches import cv2_imshow
rectangle=cv2.rectangle(blank2,(0,0),(230,340),(140,255,333),thickness=3)
rect=cv2_imshow(rectangle)

# Drawing a circle
circle= cv2.circle(blank2,(15,15),30,(0,0,255),thickness=-1)
cv2_imshow(circle)

#Draw a line
line= cv2.line(blank2, (450,450),(500,500),(255,0,0),thickness=2)
cv2_imshow(line)

ret, thresh = cv2.threshold(gray, 125, 255, cv2.THRESH_BINARY)    # Threshold essentially looks at image and tries to binarise it
cv2_imshow(thresh)

contours, hierarchies= cv2.findContours(canny,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
print(f'{len(contours)} contour(s) found!')

draw_contour=cv2.drawContours(blank2,contours,-1,(255,0,255),1)
cv2_imshow(draw_contour)

# write text
text= cv2.putText(gray,'Hello. I am a cat!!',(0,150),cv2.FONT_HERSHEY_PLAIN,1.0,(0,255,0),2)
cv2_imshow(text)

#  masking

blnk= np.zeros(img.shape[:2],dtype='uint8')
cv2_imshow(blnk)

mask= cv2.circle(blnk,(img.shape[1]//2,img.shape[0]//2+30),100,255,thickness=-1)
cv2_imshow(mask)
masked= cv2.bitwise_and(img,img,mask=mask)
cv2_imshow(masked)

## different shapes
circle2= cv2.circle(blnk.copy(),(img.shape[1]//2,img.shape[0]//2),50,255,thickness=-1)
cv2_imshow(circle2)

rectangle2=cv2.rectangle(blnk.copy(),(40,40),(130,130),255,thickness=-1)
cv2_imshow(rectangle2)

shape= cv2.bitwise_and(circle2,rectangle2)
cv2_imshow(shape)

masked2= cv2.bitwise_and(img,img,mask=shape)
cv2_imshow(masked2)

# reading video
video=cv2.VideoCapture('/content/drive/MyDrive/Hrutuja Vanjale /OpenCV/pexels-dario-fernandez-ruz-6869468.mp4')

capture= cv2.VideoCapture('/content/pexels-dario-fernandez-ruz-6869468.mp4')

while True:
  isTrue, frame=video.read()
  if isTrue:    
        cv2_imshow(frame)
        if cv2.waitKey(1):
            break 
  else:
    break           
        

  video.release()
  cv2.destroyAllWindows()   ## try this in python using vscode

